language: objective-c
osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - ~/.rvm
    - ~/.cocoapods
    - ~/Library/Caches/CocoaPods
    - .bundle
    - vendor
env:
  global:
    - WORKSPACE='RealmS.xcworkspace'
    - SCHEME='RealmS'
    - SDK='iphonesimulator10.2'
    - DESTINATION='OS=10.2,name=iPhone 7'
install:
  - ./scripts/install
script:
  - export REPO_SLUG="$TRAVIS_REPO_SLUG"
  - export SRC_BRANCH="$(./scripts/src_branch)"
  - export PR_NUMBER="$(./scripts/pr_number)"
  - ./scripts/lint
  - ./scripts/test
  - ./scripts/pod_test
  - bundle exec pod lib lint --quick
notifications:
  email: false
after_success:
  - ./scripts/codecov
