language: swift
os: osx
osx_image: xcode13.2.1
cache:
  bundler: true
  directories:
    - ~/.rvm
    - .bundle
    - vendor
install:
  - set -o pipefail
  - ./scripts/install
script:
  - export REPO_SLUG="$TRAVIS_REPO_SLUG"
  - export SRC_BRANCH="$(./scripts/src_branch)"
  - export PR_NUMBER="$(./scripts/pr_number)"
  - ./scripts/tests/lint
  - swift build
  - swift test
notifications:
  email: false
after_success:
  - ./scripts/codecov
